[tools]
"github:JohnnyMorganz/luau-lsp" = "latest"
"github:axodotdev/cargo-dist" = "0.30.3"
"github:jacktabscode/drillbit" = "0.1.5"
"github:rojo-rbx/rojo" = "7"
stylua = "latest"

[tasks.build-plugin]
run = "rojo build -o plugin.rbxm"

[tasks.dev]
run = "drillbit"
depends = ["build-plugin"]
sources = ["plugin/**/*", "default.project.json"]
